### PR TITLE
Added GhostText

### PR DESCRIPTION
**Pull request by stappersg**
For using Helix in your webbrowser.
Text from https://ghosttext.fregante.com/

  Whenever you’re writing more than a little snippet of code anywhere
  on the web, activate GhostText to open your preferred text editor and
  enjoy your own development environment.

### CODE REVIEW

**Comment by zim0369** [comment]
Please add the name to the "Plugin list" section.

**Comment by stappersg** [comment]
> Please add a name to the "Plugin list" section with an anchor link.

Oh, those weren't generated in _Table of Content_ fashion.

**Comment by stappersg** [comment]
> Please add a name to the "Plugin list" section with an anchor link.

Done. At https://github.com/stappersg/helix_plugins/tree/GhostText can be seen
there is an autonumbering of the items. (there is no need to renumber the items.)

Additional information in the screenshot:

afbeelding

**Comment by zim0369** [comment]
@stappersg remark-lsp renumbers files on save 😅

**Pull request merged**
